name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - name: Setup java JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Maven
        run: ./mvnw clean install
      - uses: mr-smithers-excellent/docker-build-push@v6
        name : Create docker image
        with:
          registry: docker.io
          image: vaibhavces/employee-management-system
          tags: latest
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


