name: Post-merge-commit pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v3
      - name: Setup java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Clean compile application
        run: ./mvnw clean install
      - name: Run Tests
        run: ./mvnw test
      - name: Publish Test Reports
        run: ./mvnw jacoco:report
      - uses: actions/upload-artifact@v3
        with:
          name: test-artifact-jacoco-reports
          path: target
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Push image to docker
        with:
          image: vaibhavces/employee-management-system
          tags: latest
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          pushImage: true